---
# all below value can access by {{ size.key }}

name: jetzhliu.github.io
description: my github persional page
url: ""
baseurl: "" # your project name or none for User Page

paginate: 5

drafts: True
# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post

# github config
highlighter: pygments
safe: true
lsi: false
gems:
  - jemoji
  - jekyll-sitemap

...

_assets: _assets

sass:
  sass_dir: _sass
  style: :expanded :compressed
